name: Remark
on:
  push:
    branches:
      - master
      - release/*
jobs:
  remark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remark
        uses: ocular-d/action-remark@0.0.10
